# Generated by Django 4.2.4 on 2023-08-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=50, null=True)),
                ('price', models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='DateCreated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
